# Generated by Django 2.2.12 on 2022-03-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('distance', models.CharField(max_length=100)),
                ('condition', models.BooleanField(default=False)),
                ('cost', models.FloatField(default=0.0)),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('calculated_cost', models.FloatField(default=0.0)),
            ],
        ),
    ]
