# Generated by Django 2.2.12 on 2022-02-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_name',
        ),
    ]
