# Generated by Django 2.2.12 on 2022-02-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_remove_route_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.CharField(max_length=100),
        ),
    ]
