# Generated by Django 2.2.12 on 2022-02-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_routedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='routedata',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
